openapi: 3.0.0
info:
  title: nilDB API
  version: 0.5.0
  description: |
    Visit [docs.nillion.com](https://docs.nillion.com) and [github.com/NillionNetwork/nildb](https://github.com/NillionNetwork/nildb) to learn more.

servers:
  - url: /

tags:
  - name: Accounts
    description: Account details
  - name: Data
    description: Create, read, update and delete data for specified schemas
  - name: Query
    description: Manage and execute queries
  - name: Schema
    description: Manage your schemas
  - name: Node
    description: Node information
  - name: Admin
    description: Admin management
  - name: Beta
    description: Features under incubation

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        A DID-JWT using the ES256K algorithm for authenticated endpoints.
        JWT payload must include:
        - iat: Issued at timestamp
        - exp: Expiration timestamp (recommended)
        - aud: Target node decentralised identifier (DID)
        - iss: Client's decentralised identifier (DID)
  schemas:
    UUID:
      description: A universally unique identifier for the item.
      type: string
      format: uuid
    Filter:
      type: object
      minProperties: 1
      additionalProperties: true
      description: MongoDB-style query filter
      properties:
        $coerce:
          type: object
          description:
            A flexible object allowing any key-value pairs, where the keys refers to a property in the filter
            and the value is the MongoDB primitive type which the property will be transformed.
            Only the primitive types 'date' and 'uuid' are supported.
            The required properties (_id, _created and _update) are supported automatically.
    DocumentBase:
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/UUID'
        _created:
          type: string
          format: date-time
          description: The creation timestamp.
        _updated:
          type: string
          format: date-time
          description: The last update timestamp.
      required:
        - _id
        - _created
        - _updated
    Schema:
      allOf:
        - $ref: '#/components/schemas/DocumentBase'
        - type: object
          required:
            - name
            - owner
            - schema
          properties:
            name:
              description: A user friendly schema name
              type: string
            owner:
              description: The decentralised identifier (DID) of the owning organization
              type: string
              example: 'did:nil:nillion1eunreuzltxglx9fx493l2r8ef6rdlrau4dsdnc'
            schema:
              description: The json schema used to validate data before insertion into the schema collection
              type: object

    DataDocument:
      allOf:
        - $ref: '#/components/schemas/DocumentBase'
        - type: object
          additionalProperties: true
          description: The document's additional properties. Schema dependent.

    Error:
      type: object
      required:
        - ts
        - errors
      properties:
        ts:
          type: string
          format: date-time
          description: The error's timestamp.
        errors:
          description: A list of error messages
          type: array
          items:
            anyOf:
              - type: string
              - type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
  responses:
    201:
      description: Resource created
    204:
      description: Resource deleted
    400:
      description: Validation or processing errors
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401:
      description: Missing or invalid JWT
    404:
      description: Resource not found
    500:
      description: Internal server error

paths:
  # Account endpoints
  /api/v1/accounts:
    $ref: '../accounts/accounts.openapi.yaml#/paths/~1api~1v1~1accounts'
  /api/v1/accounts/publicKey:
    $ref: '../accounts/accounts.openapi.yaml#/paths/~1api~1v1~1accounts~1publicKey'

  # Schema endpoints
  /api/v1/schemas:
    $ref: '../schemas/schemas.openapi.yaml#/paths/~1api~1v1~1schemas'

  # Query endpoints
  /api/v1/queries:
    $ref: '../queries/queries.openapi.yaml#/paths/~1api~1v1~1queries'
  /api/v1/queries/execute:
    $ref: '../queries/queries.openapi.yaml#/paths/~1api~1v1~1queries~1execute'

  # Data endpoints
  /api/v1/data/create:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1create'
  /api/v1/data/read:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1read'
  /api/v1/data/update:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1update'
  /api/v1/data/tail:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1tail'
  /api/v1/data/delete:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1delete'
  /api/v1/data/flush:
    $ref: '../data/data.openapi.yaml#/paths/~1api~1v1~1data~1flush'

  # System endpoints
  /health:
    $ref: '../system/system.openapi.yaml#/paths/~1health'
  /about:
    $ref: '../system/system.openapi.yaml#/paths/~1about'

  # Admin endpoints
  /api/v1/admin/maintenance:
    $ref: '../admin/admin.system.openapi.yaml#/paths/~1api~1v1~1admin~1maintenance'
  /api/v1/admin/log_level:
    $ref: '../admin/admin.system.openapi.yaml#/paths/~1api~1v1~1admin~1log_level'

  # Beta endpoints
  /api/beta/schemas/{id}/meta:
    $ref: 'beta.openapi.yaml#/paths/~1api~1beta~1schemas~1{id}~1meta'
  /api/beta/schemas/{id}/indexes:
    $ref: 'beta.openapi.yaml#/paths/~1api~1beta~1schemas~1{id}~1indexes'
  /api/beta/schemas/{id}/indexes/{name}:
    $ref: 'beta.openapi.yaml#/paths/~1api~1beta~1schemas~1{id}~1indexes~1{name}'
