deployment:
  name: nildb-node-guue
  container:
    image: "@{TF_VAR_deployment_image_repo}"
    tag: "@{TF_VAR_deployment_image_tag}"
    port: 8080

    resources:
      cpu: 1024
      memory: 1024

    environment:
      APP_DB_NAME_DATA: datablocks_data
      APP_DB_NAME_PRIMARY: datablocks
      APP_ENV: testnet
      APP_METRICS_PORT: 9091
      APP_PORT: 8080

    secrets:
      APP_DB_URI: db_uri
      APP_NODE_SECRET_KEY: node_secret_key
      APP_ROOT_USER_SECRET_KEY: root_user_secret_key

    prometheus:
      metrics_port: 9091
      metrics_path: /metrics

  scaling:
    desired_count: 1

vars:

  sandbox:
    zone_name: "sandbox.nilogy.xyz"
    name_prefix: sandbox
    secrets_recovery_window_in_days: 0
    deployment:
      network:
        public_access: true
        allowed_cidrs: ["0.0.0.0/0"]
      container:
        environment:
          APP_LOG_LEVEL: debug
          APP_NODE_PUBLIC_ENDPOINT: https://nildb-node-guue.sandbox.app-cluster.sandbox.nilogy.xyz

  production:
    zone_name: "nillion.network"
    name_prefix: production
    deployment:
      network:
        public_access: true
        allowed_cidrs: ["0.0.0.0/0"]
        additional_domains: [ nildb-guue.nillion.network ]
      container:
        environment:
          APP_LOG_LEVEL: warn
          APP_NODE_PUBLIC_ENDPOINT: https://nildb-guue.nillion.network
