deployment:
  name: nil-db
  container:
    image: "@{TF_VAR_deployment_image_repo}"
    tag: "@{TF_VAR_deployment_image_tag}"
    port: 8080

    resources:
      cpu: 1024
      memory: 1024

    environment:
      APP_DB_NAME_PREFIX: datablocks
      APP_ENV: dev
      APP_LOG_LEVEL: debug
      APP_PORT: 8080
      APP_METRICS_PORT: 9091
      APP_NODE_PUBLIC_ENDPOINT: https://nil-db.sandbox.app-cluster.sandbox.nilogy.xyz
      APP_NODE_PUBLIC_ADDRESS: nillion1130x40qcgq0lcpf7rlhpgmvp2q0hz924jd6vvra

    secrets:
      APP_NODE_PRIVATE_KEY: node_private_key
      APP_DB_URI: db_uri
      APP_JWT_SECRET: jwt_secret

    prometheus:
      metrics_port: 9091
      metrics_path: /metrics

  scaling:
    desired_count: 1

  network:
    public_access: true
    allowed_cidrs: ["0.0.0.0/0"]

vars:
  sandbox:
    zone_name: "sandbox.nilogy.xyz"
    name_prefix: sandbox
    secrets_recovery_window_in_days: 0
