components:
  schemas:
    Account:
      type: object
      required:
        - _id
        - _role
        - _created
        - _updated
        - publicKey
        - name
        - schemas
        - queries
      properties:
        _id:
          description: The accounts decentralised identifier (DID)
          type: string
          example: 'did:nil:nillion1eunreuzltxglx9fx493l2r8ef6rdlrau4dsdnc'
        _role:
          type: string
          enum: [ 'admin', 'organization' ]
        _created:
          type: string
          format: date-time
        _updated:
          type: string
          format: date-time
        publicKey:
          type: string
        name:
          type: string
        schemas:
          description: A list of schema ids that belong to this account
          type: array
          items:
            $ref: '../docs/base.openapi.yaml#/components/schemas/UUID'
        queries:
          description: A list of query ids that belong to this account
          type: array
          items:
            $ref: '../docs/base.openapi.yaml#/components/schemas/UUID'

paths:
  /api/v1/accounts:
    get:
      summary: Get account information
      description: Retrieve an organization's account details
      tags:
        - Accounts
      security:
        - jwt: [ ]
      responses:
        '200':
          description: "The organization's account details"
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Account'
        '400':
          $ref: '../docs/base.openapi.yaml#/components/responses/400'
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
  /api/v1/accounts/publicKey:
    post:
      summary: Update organization's public key
      description: Update an organization's public key
      security:
        - jwt: [ ]
      tags:
        - Data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - did
                - publicKey
              properties:
                data:
                  $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: The public key has been updated
        '400':
          $ref: '../docs/base.openapi.yaml#/components/responses/400'
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
