paths:
  /api/v1/admin/maintenance:
    post:
      summary: Set node maintenance window
      description: Set node maintenance window for a single node
      operationId: setMaintenanceWindow
      security:
        - jwt: [ ]
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start
                - end
              properties:
                start:
                  type: string
                  format: date-time
                  description: Maintenance window starts at
                  example: '2025-02-14T00:00:00.000Z'
                end:
                  type: string
                  format: date-time
                  description: Maintenance window ends at
                  example: '2025-02-14T00:30:00.000Z'
      responses:
        '200':
          description: Maintenance window successfully set
        '400':
          $ref: '../docs/base.openapi.yaml#/components/responses/400'
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
    delete:
      summary: Delete node maintenance window
      description: End node maintenance instantly by deleting it's maintenance window
      operationId: deleteMaintenanceWindow
      security:
        - jwt: [ ]
      tags:
        - Admin
      responses:
        '204':
          $ref: '../docs/base.openapi.yaml#/components/responses/204'
        '400':
          $ref: '../docs/base.openapi.yaml#/components/responses/400'
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
  /api/v1/admin/log_level:
    get:
      summary: Get log level
      description: Get node's current log `level` and `levelValue`
      operationId: getLogLevel
      tags:
        - Admin
      security:
        - jwt: [ ]
      responses:
        '200':
          description: Node's current log level
          content:
            application/json:
              schema:
                type: object
                required:
                  - level
                  - levelValue
                properties:
                  level:
                    type: string
                    description: Log level label
                    example: info
                  levelValue:
                    type: number
                    description: Log level value
                    example: 30
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
    post:
      summary: Set log level
      description: Set node's log level at runtime
      operationId: setLogLevel
      security:
        - jwt: [ ]
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - level
              properties:
                level:
                  type: string
                  description: Log level label
                  example: info
      responses:
        '200':
          description: Log level successfully set
        '400':
          $ref: '../docs/base.openapi.yaml#/components/responses/400'
        '401':
          $ref: '../docs/base.openapi.yaml#/components/responses/401'
        '500':
          $ref: '../docs/base.openapi.yaml#/components/responses/500'
