deployment:
  name: nildb-node-demo
  container:
    image: "@{TF_VAR_deployment_image_repo}"
    tag: "@{TF_VAR_deployment_image_tag}"
    port: 8080

    resources:
      cpu: 1024
      memory: 1024

    secrets:
      APP_DB_URI: db_uri
      APP_NODE_SECRET_KEY: node_secret_key
      APP_ROOT_USER_SECRET_KEY: root_user_secret_key

    prometheus:
      metrics_port: 9091
      metrics_path: /metrics

    headers:
      insert:
        "Access-Control-Allow-Origin": "https://docs.nillion.com"
        "Access-Control-Allow-Methods": "GET, POST, DELETE"
        "Access-Control-Allow-Headers": "Authorization, Content-Type, Accept"
        "Access-Control-Max-Age": "3600"
        "Access-Control-Allow-Credentials": "true"

      disable: ["server"]

  scaling:
    desired_count: 1

vars:

  production:
    zone_name: "nillion.network"
    name_prefix: production
    deployment:
      network:
        public_access: true
        allowed_cidrs: ["0.0.0.0/0"]
        additional_domains: [ nildb-demo.nillion.network ]
      container:
        environment:
          APP_DB_NAME_DATA: datablocks_data
          APP_DB_NAME_PRIMARY: datablocks
          APP_ENV: testnet
          APP_LOG_LEVEL: info
          APP_METRICS_PORT: 9091
          APP_NODE_PUBLIC_ENDPOINT: https://nildb-demo.nillion.network
          APP_PORT: 8080
