name: Infra

on:
  push:

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: NillionNetwork/devops/actions/terraform/frameworks/ecs_service@feat/frameworks
        with:
          dir: infra

      - name: Get Version
        id: version
        run: echo "value=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - uses: NillionNetwork/devops/actions/terraform/frameworks@feat/frameworks
        env:
          TF_VAR_deployment_image_tag: ${{ steps.version.outputs.value }}
        with:
          framework: ecs_service
          deploy_env: sandbox
          deploy_roles: |-
            { "sandbox": "arn:aws:iam::767397865113:role/sandbox-nil-db-github" }
          devops_version: feat/frameworks
          gha_app_id: ${{ secrets.NILLION_GITHUB_ACTIONS_APP_ID }}
          gha_app_private_key: ${{ secrets.NILLION_GITHUB_ACTIONS_APP_PRIVATE_KEY }}
          tf_secrets_master_password: ${{ secrets.SECRETS_MASTER_PASSWORD }}
