name: CD - Update ECS Task

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "ECR image tag to schedule"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: "arn:aws:iam::767397865113:role/DevOps"
          aws-region: "eu-west-1"
          role-skip-session-tagging: true

      - run: |
          aws ecs describe-task-definition \
            --task-definition nil-db-sandbox-nil-db \
            --query taskDefinition > task-definition.json

      - uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: task-def
        with:
          task-definition: task-definition.json
          container-name: api
          image: 592920173613.dkr.ecr.eu-west-1.amazonaws.com/datablocks-api:${{ inputs.tag }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: app-cluster-sandbox
          service: nil-db-sandbox-nil-db
          wait-for-service-stability: true
