name: CD - Publish Docker Image to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: "arn:aws:iam::592920173613:role/DevOps"
          aws-region: "eu-west-1"
          role-skip-session-tagging: true

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - uses: docker/setup-buildx-action@v3

      - name: Create build info
        run: |
          VERSION=$(cat package.json | jq -r .version)
          cat << EOF > buildinfo.json
          {
            "time": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')",
            "commit": "${{ github.sha }}",
            "version": "${VERSION}"
          }
          EOF

      - name: Build and push images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: datablocks-api
          IMAGE_TAG_SHA: ${{ github.sha }}
        run: |
          # Always tag with commit sha
          TAGS="-t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG_SHA}"
          
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # On manual trigger, use version from package.json
            IMAGE_TAG_VERSION=$(cat package.json | jq -r .version)
            TAGS="$TAGS -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG_VERSION}"
          else
            # If triggered by push to main, use latest tag
            TAGS="$TAGS -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          fi
          
          docker build \
            --push \
            -f Dockerfile \
            $TAGS \
            .

          echo "Used tags: $TAGS" >> $GITHUB_STEP_SUMMARY
