name: "node-dvml: Deploy to ECS"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "ECR image tag to schedule"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify deployment.yaml
        uses: NillionNetwork/devops/actions/terraform/frameworks/ecs_service@master
        with:
          dir: infra/node-dvml

      - name: Deploy ECS service
        uses: NillionNetwork/devops/actions/terraform/frameworks@master
        env:
          TF_VAR_deployment_dir: infra/node-dvml
          TF_VAR_deployment_image_tag: ${{ inputs.tag }}
          TF_VAR_deployment_image_repo: 470421895671.dkr.ecr.eu-west-1.amazonaws.com/nildb-api
        with:
          framework: ecs_service
          deploy_env: production
          deploy_roles: |
            { "production": "arn:aws:iam::470421895671:role/nil-db-github" }
          gha_app_id: ${{ secrets.NILLION_GITHUB_ACTIONS_APP_ID }}
          gha_app_private_key: ${{ secrets.NILLION_GITHUB_ACTIONS_APP_PRIVATE_KEY }}
          tf_secrets_master_password: ${{ secrets.SECRETS_MASTER_PASSWORD }}
          tg_command: ${{ github.ref == 'refs/heads/main' && 'apply -auto-approve' || 'plan' }}
